CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    countries VARCHAR(255) NOT NULL,
    school VARCHAR(255) NOT NULL,
    phone INT NOT NULL,
    grade INT NOT NULL
);